# Generated by Django 5.2.8 on 2026-01-10 13:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MatriculeAutorise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(max_length=50, unique=True, verbose_name='Matricule')),
                ('est_actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_activation', models.DateTimeField(blank=True, null=True, verbose_name="Date d'activation")),
                ('activation_token', models.CharField(blank=True, max_length=100, null=True, verbose_name="Token d'activation")),
                ('token_expiration', models.DateTimeField(blank=True, null=True, verbose_name='Expiration du token')),
            ],
            options={
                'verbose_name': 'Matricule autorisé',
                'verbose_name_plural': 'Matricules autorisés',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Message')),
                ('notification_type', models.CharField(choices=[('system', 'Système'), ('profile_update', 'Mise à jour profil'), ('project', 'Projet'), ('message', 'Message')], default='system', max_length=20)),
                ('is_read', models.BooleanField(default=False, verbose_name='Lu')),
                ('metadata', models.JSONField(blank=True, null=True, verbose_name='Métadonnées')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProfileUpdateHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('changes', models.JSONField(verbose_name='Modifications')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresse IP')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='User Agent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='update_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historique de modification',
                'verbose_name_plural': 'Historiques de modification',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='Biographie')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Téléphone')),
                ('location', models.CharField(blank=True, max_length=100, null=True, verbose_name='Localisation')),
                ('company', models.CharField(blank=True, max_length=100, null=True, verbose_name='Entreprise')),
                ('position', models.CharField(blank=True, max_length=100, null=True, verbose_name='Poste')),
                ('cohort', models.CharField(blank=True, max_length=100, null=True, verbose_name='Promotion Simplon')),
                ('specialite', models.CharField(blank=True, max_length=100, null=True, verbose_name='Spécialité')),
                ('date_entree', models.DateField(blank=True, null=True, verbose_name="Date d'entrée")),
                ('date_sortie', models.DateField(blank=True, null=True, verbose_name='Date de sortie')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Site web personnel')),
                ('github', models.URLField(blank=True, null=True, verbose_name='GitHub')),
                ('linkedin', models.URLField(blank=True, null=True, verbose_name='LinkedIn')),
                ('twitter', models.URLField(blank=True, null=True, verbose_name='Twitter/X')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Photo de profil')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='extended_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil utilisateur étendu',
                'verbose_name_plural': 'Profils utilisateurs étendus',
            },
        ),
    ]
