# Generated by Django 5.2.8 on 2025-11-12 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatriculeAutorise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(max_length=50, unique=True, verbose_name='Matricule Simplon')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('est_actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('date_activation', models.DateTimeField(blank=True, null=True, verbose_name="Date d'activation")),
            ],
            options={
                'verbose_name': 'Matricule autorisé',
                'verbose_name_plural': 'Matricules autorisés',
            },
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
