# Generated by Django 5.2.8 on 2025-11-13 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_matriculeautorise_delete_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='matriculeautorise',
            name='activation_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='matriculeautorise',
            name='token_expiration',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
