# Generated by Django 5.2.8 on 2026-01-10 13:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('description', models.TextField(verbose_name='Description')),
                ('technologies', models.CharField(max_length=300, verbose_name='Technologies utilisées')),
                ('github_url', models.URLField(blank=True, verbose_name='Lien GitHub')),
                ('demo_url', models.URLField(blank=True, verbose_name='Lien de démo')),
                ('image', models.ImageField(blank=True, null=True, upload_to='projects/', verbose_name='Image du projet')),
                ('author_name', models.CharField(blank=True, help_text="Rempli automatiquement depuis l'utilisateur", max_length=255, verbose_name="Nom complet de l'auteur")),
                ('author_email', models.EmailField(blank=True, help_text="Rempli automatiquement depuis l'utilisateur", max_length=254, verbose_name="Email de l'auteur")),
                ('author_username', models.CharField(blank=True, help_text="Rempli automatiquement depuis l'utilisateur", max_length=150, verbose_name="Nom d'utilisateur")),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('pending', 'En attente'), ('approved', 'Approuvé'), ('rejected', 'Rejeté'), ('published', 'Publié'), ('archivé', 'Archivé')], default='draft', max_length=20, verbose_name='Statut')),
                ('cohort', models.CharField(blank=True, max_length=100, verbose_name='Cohorte')),
                ('tags', models.TextField(blank=True, verbose_name='Tags')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL, verbose_name='Auteur (ID)')),
            ],
            options={
                'verbose_name': 'Projet',
                'verbose_name_plural': 'Projets',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['author'], name='projects_pr_author__991a6d_idx'), models.Index(fields=['author_name'], name='projects_pr_author__8e62ab_idx'), models.Index(fields=['status'], name='projects_pr_status_f023cb_idx'), models.Index(fields=['cohort'], name='projects_pr_cohort_856838_idx'), models.Index(fields=['created_at'], name='projects_pr_created_6b02e3_idx')],
            },
        ),
    ]
