# Generated by Django 5.2.8 on 2026-01-28 13:22

import projects.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('web', 'Web'), ('mobile', 'Mobile'), ('desktop', 'Desktop'), ('data', 'Data Science'), ('ai', 'IA/ML'), ('game', 'Jeux'), ('other', 'Autre')], default='web', max_length=50, verbose_name='Catégorie'),
        ),
        migrations.AddField(
            model_name='project',
            name='downloads',
            field=models.IntegerField(default=0, verbose_name='Nombre de téléchargements'),
        ),
        migrations.AddField(
            model_name='project',
            name='likes',
            field=models.IntegerField(default=0, verbose_name='Nombre de likes'),
        ),
        migrations.AddField(
            model_name='project',
            name='views',
            field=models.IntegerField(default=0, verbose_name='Nombre de vues'),
        ),
        migrations.AddField(
            model_name='project',
            name='zip_file',
            field=models.FileField(blank=True, help_text='Archive ZIP contenant le code source du projet (max 500MB)', max_length=500, null=True, upload_to=projects.models.project_zip_upload_path, verbose_name='Fichier ZIP du projet'),
        ),
        migrations.AlterField(
            model_name='project',
            name='author_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name="Email de l'auteur"),
        ),
        migrations.AlterField(
            model_name='project',
            name='author_name',
            field=models.CharField(blank=True, max_length=255, verbose_name="Nom complet de l'auteur"),
        ),
        migrations.AlterField(
            model_name='project',
            name='author_username',
            field=models.CharField(blank=True, max_length=150, verbose_name="Nom d'utilisateur"),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, help_text='Image de présentation du projet', max_length=500, null=True, upload_to=projects.models.project_image_upload_path, verbose_name='Image du projet'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['category'], name='projects_pr_categor_220446_idx'),
        ),
    ]
